use geoDB;

#create table adxGeoData

CREATE TABLE adxGeoData (id INT);
ALTER TABLE adxGeoData ADD COLUMN CriteriaID INT;
ALTER TABLE adxGeoData ADD COLUMN Name VARCHAR(256);
ALTER TABLE adxGeoData ADD COLUMN CanonicalName VARCHAR(256);
ALTER TABLE adxGeoData ADD COLUMN ParentIDs VARCHAR(256);
ALTER TABLE adxGeoData ADD COLUMN BlankField VARCHAR(256);
ALTER TABLE adxGeoData ADD COLUMN CountryCode VARCHAR(256);
ALTER TABLE adxGeoData ADD COLUMN TargetType VARCHAR(256);
ALTER TABLE adxGeoData ENGINE=InnoDB;
ALTER TABLE adxGeoData CONVERT TO CHARACTER SET utf8;

#create table iso3166-3CountryData

CREATE TABLE iso3166-3CountryData (id INT);
ALTER TABLE iso3166-3CountryData ADD COLUMN CountryCode VARCHAR(256);
ALTER TABLE iso3166-3CountryData ADD COLUMN CountryName VARCHAR(256);
ALTER TABLE iso3166-3CountryData ADD COLUMN OtherName VARCHAR(256);
ALTER TABLE iso3166-3CountryData ENGINE=InnoDB;
ALTER TABLE iso3166-3CountryData CONVERT TO CHARACTER SET utf8;

#create table iso31662RegionData

CREATE TABLE iso31662RegionData (id INT);
ALTER TABLE iso31662RegionData ADD COLUMN RegionCode VARCHAR(256);
ALTER TABLE iso31662RegionData ADD COLUMN CountryCode VARCHAR(256);
ALTER TABLE iso31662RegionData ADD COLUMN RegionName VARCHAR(256);
ALTER TABLE iso31662RegionData ADD COLUMN RegionLevel VARCHAR(256);
ALTER TABLE iso31662RegionData ENGINE=InnoDB;
ALTER TABLE iso31662RegionData CONVERT TO CHARACTER SET utf8;

#create table fipsRegionData
CREATE TABLE fipsRegionData (id INT);
ALTER TABLE fipsRegionData ADD COLUMN CountryCode VARCHAR(256);
ALTER TABLE fipsRegionData ADD COLUMN RegionCode VARCHAR(256);
ALTER TABLE fipsRegionData ADD COLUMN RegionName VARCHAR(256);
ALTER TABLE fipsRegionData ENGINE=InnoDB;
ALTER TABLE fipsRegionData CONVERT TO CHARACTER SET utf8;
